### ISSUE TITLE
 error: 'FALLOC_FL_COLLAPSE_RANGE' was not declared in this scope

### ISSUE THREAD

**Issue by Chr1s-T** [sslab-gatech/hydra#1]
I tried to install hydra and make install by executing the command `make build-btrfs-imgwrp`
But it failed and throwed the error message " error: 'FALLOC_FL_COLLAPSE_RANGE' was not declared in this scope". What's the problem here?
![image](https://user-images.githubusercontent.com/23159278/69114912-ce0ac680-0ac1-11ea-86cb-48090b5f57a7.png)
Besides, I have installed clang already, with a soft link to the path `..../hydra-master/src/llvm-build/bin/`
![image](https://user-images.githubusercontent.com/23159278/69114948-ea0e6800-0ac1-11ea-98c5-9ed7715ce82f.png)

**Comment by squizz617** [comment]
That seems to be an issue with the older versions of clang, being not aware of the recent fs flags such as FALLOC_FL_COLLAPSE_RANGE.
Instead of using the system's clang, could you retry building hydra with the llvm included in the repo?

**Comment by Chr1s-T** [comment]
Should I build the llvm in the directory `llvm-build`? But I cannot make install directly, what should I do...?
![image](https://user-images.githubusercontent.com/23159278/69204730-bf381880-0b82-11ea-9e39-ce299db20174.png)

**Comment by squizz617** [comment]
As per the error message, cmake 2.8.12 is too old (was released in 2013) to compile llvm toolchain that we utilize. I would suggest you to install a newer version of cmake (3.4.3 or higher) in your system. If you are running ubuntu 16.04 or later version, running `apt update && sudo apt upgrade` will suffice.

**Comment by Chr1s-T** [comment]
Holy God, plz help me! It turns out no use for some errors.
As you can see, I have compiled and installed the cmake and clang completely:
![image](https://user-images.githubusercontent.com/23159278/69401359-db2ced00-0d2f-11ea-8866-4f1e22ece7d6.png)
![image](https://user-images.githubusercontent.com/23159278/69401386-f0a21700-0d2f-11ea-8761-c6b815698704.png)
And I have `make install` in the llvm-build directory successfully:
![image](https://user-images.githubusercontent.com/23159278/69401497-2c3ce100-0d30-11ea-95e8-906bb15c5bb1.png)
But when I tried to `sudo make build-ext4-imgwrp`, it's still failed:
![image](https://user-images.githubusercontent.com/23159278/69401589-702fe600-0d30-11ea-9d20-10ae4185fe51.png)
What's the problem in here? It's too hard for me...

**Comment by squizz617** [comment]
I wonder if the proper cmake arguments were set when your were manually building llvm.
Would you try cloning hydra repository again, and building from scratch?
