### ISSUE TITLE
c5d1b0c make build-xfs-imgwrp failed

### ISSUE THREAD

**Issue by uestcmahone** [sslab-gatech/hydra#11]
```
make -C afl-syscall
g++ -std=c++11 -g -fPIC -c -o FSCQ-consistency-exec.o FSCQ-consistency-exec.cpp
g++ -std=c++11 -g -fPIC -c -o yxv6-consistency-exec.o yxv6-consistency-exec.cpp
make[2]: Entering directory '/home/m00292095/git/hydra/src/combined'
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[2]: *** afl-syscall: No such file or directory.  Stop.
make[2]: Leaving directory '/home/m00292095/git/hydra/src/combined'
Makefile:33: recipe for target 'afl' failed
make[1]: *** [afl] Error 2
make[1]: *** Waiting for unfinished jobs....
```
may caused by ed561e5 update Makefile?

```
git diff combined/Makefile
diff --git a/src/combined/Makefile b/src/combined/Makefile
index 0f4b411..08371f3 100644
--- a/src/combined/Makefile
+++ b/src/combined/Makefile
@@ -30,7 +30,7 @@ yxv6-cc: yxv6-consistency-exec.o Image.o Program.o Utils.o Constants.o
        $(CXX) $(CXXFLAGS) -o $@ $^

 afl:
-       make -C afl-syscall
+       make -C afl-image-syscall

 %.o: %.cpp
        $(CXX) $(CXXFLAGS) -fPIC -c -o $@ $<
```

**Comment by jahidhasanlinix** [comment]
@squizz617 I actually having an issue on #3 makefile one, getting this error-
`(cd /home/desktop/hydra/src/lkl && ./compile -t xfs -c && cd -)
/bin/sh: 1: ./compile: not found
make: *** [Makefile:61: build-lkl-xfs] Error 127`

Even i tried to use `make clean` it also does not work. I tried it for all, but none of them are working on step 3. Any suggestion how to fix it. Thanks.

**Comment by jahidhasanlinix** [comment]
@squizz617  Second Issue is: `hydra/src/lkl$ git checkout v4.16-backport
error: pathspec 'v4.16-backport' did not match any file(s) known to git

hydra/src/lkl$ ./compile -t btrfs
-bash: ./compile: /usr/bin/python: bad interpreter: No such file or directory`

Part of Step 3, not wroking
