### ISSUE TITLE
How to test FUSE filesystems?

### ISSUE THREAD

**Issue by gaul** [sslab-gatech/hydra#13]
The instructions seem geared towards traditional filesystems like ext4 and btrfs.  Can you provide instructions for FUSE filesystems, e.g., s3fs?  The paper suggests that this is possible.

**Comment by bonzobudy225** [comment]
@gaul did you figure out how to get FUSE fuzzing working?

**Comment by squizz617** [comment]
To test FUSE file systems, you need to write your own userspace executor program, which receives the mutated image + syscalls from the input mutator, mounts the mutated image and executes the system calls. The workflow then depends entirely on how the target file system is written.

For example, the following are the steps to test FSCQ, which is a verified file system that operates on the userspace:
- compile it using clang with pass `combined/afl-fscq-syscall/afl-llvm-pass.so`, to get the fuse driver `fscq`. When executed, `fscq` mounts the given FS image in the userspace,
- write the executor `src/combined/FSCQ-consistency-exec` and compile it as `fscq-cc` (please note that this executor has additional procedures as it targets crash consistency bugs),
- run `fscq-cc` in one terminal,
- launch Hydra, providing `fscq` and relevant arguments as a target program.

[This note](https://github.com/sslab-gatech/hydra/blob/master/src/fscq-cc-run-note) and [FSCQ executor](https://github.com/sslab-gatech/hydra/blob/master/src/combined/FSCQ-consistency-exec.cpp) could be of help.
