### ISSUE TITLE
Who did u report the bug to?

### ISSUE THREAD

**Issue by ikaroso** [sslab-gatech/hydra#15]
LOVE YOUR WORK. I read the paper and noticed that most of the bugs detected by HYDR  were acknowledged or fixed. Did u report the bug to official email account of LINUX or report them on some communities?

**Comment by squizz617** [comment]
For kernel file systems, we reported bugs to each file system developers using Bugzilla. These are the [reports](https://bugzilla.kernel.org/buglist.cgi?bug_status=__all__&content=seulbae&no_redirect=1&order=Importance&product=File%20System&query_format=specific) for crash consistency bugs we found.

**Comment by ikaroso** [comment]
> 

a thousand thx bro, appreciate it
