### ISSUE TITLE
can't find setup logic bug

### ISSUE THREAD

**Issue by docfate111** [sslab-gatech/hydra#16]
In EXPERIMENTS.md it says to run setup_logicbug.sh.
I checked out the logicbug branch and 
```
$ find . -name setup_logicbug.sh
```
returns nothing. Is the file under a different name?
how do i instrument this fuzzer for other filesystems?

**Comment by squizz617** [comment]
The file's under src:
```
╭─seulbae@P1 ~/workspace/hydra  ‹master› 
╰─➤  git checkout logicbug
Updating files: 100% (51400/51400), done.
Branch 'logicbug' set up to track remote branch 'logicbug' from 'origin'.
Switched to a new branch 'logicbug'
╭─seulbae@P1 ~/workspace/hydra  ‹logicbug› 
╰─➤  find . -name setup_logicbug.sh
./src/setup_logicbug.sh
╭─seulbae@P1 ~/workspace/hydra  ‹logicbug› 
╰─➤  ls src | grep logic
setup_logicbug.sh
```

To test file systems other than btrfs, ext4, f2fs and xfs, you need to implement fs wrappers (check the existing implementations in `src/fs/`) and add the fs in `lkl/compile` to instrument it using ff-gcc while building lkl.

**Comment by docfate111** [comment]
Thanks
