### ISSUE TITLE
Makefile Issue

### ISSUE THREAD

**Issue by JCJiaxin** [sslab-gatech/hydra#17]
Dear Author, I am getting some weird issue while I am in Step#3. I fixed some problems but this seems causing my time to fix it, would you like to give me some suggestions to fix it.

Error for:
`make build-xfs-imgwrp
Makefile:594: arch/x86/auto.conf: No such file or directory
make: *** No rule to make target 'arch/x86/auto.conf'.  Stop.
jahid@mai-04:~/hydra/src/lkl$ `

Thank you.

**Comment by tursunbay96** [comment]
Merhaba ben Ahmet bana yardımcı olursanız sevinirim
