### ISSUE TITLE
Fuzzer Not Displaying: Interrupted

### ISSUE THREAD

**Issue by jahidhasanlinix** [sslab-gatech/hydra#19]
So I was running fuzzer, but I am not getting the GUI interface of it. Here's the error message:

For: `./run.py -t btrfs -c 4 -l 10 -g 1`

```
[+] All right - fork server is up.

[-] Oops, the program crashed with one of the test cases provided. There are
    several possible explanations:

    - The test case causes known crashes under normal working conditions. If
      so, please remove it. The fuzzer should be seeded with interesting
      inputs - but not ones that cause an outright crash.

    - The current memory limit (256 GB) is too low for this program, causing
      it to die due to OOM when parsing valid files. To fix this, try
      bumping it up with the -m setting in the command line. If in doubt,
      try something along the lines of:

      ( ulimit -Sv $[262143 << 10]; /path/to/binary [...] <testcase )

      Tip: you can use http://jwilk.net/software/recidivm to quickly
      estimate the required amount of virtual memory for the binary. Also,
      if you are using ASAN, see docs/notes_for_asan.txt.

    - Least likely, there is a horrible bug in the fuzzer. If other options
      fail, poke <lcamtuf@coredump.cx> for troubleshooting tips.

[-] PROGRAM ABORT : Test case 'id:000000,orig:open_link_fsync0' results in a crash
         Location : perform_dry_run(), afl-fuzz.c:3017

Fuzzer stopped. You can find buggy test cases in /tmp/mosbench/tmpfs-separate/10/log
```

What could be the reason for this, I did steps 1-4 correctly without an error. @squizz617 Thanks.

**Comment by squizz617** [comment]
Could you post the output of the following?
```
$ cd src/emulator
$ ./emulator.py -i ../samples/oracle/btrfs-10.image -t btrfs -v -p $(find /tmp/mosbench/tmpfs-separate/10/log/ -name "*prog" | head -n 1)
```

**Comment by jahidhasanlinix** [comment]
> /emulator.py -i ../samples/oracle/btrfs-10.image -t btrfs -v -p $(find /tmp/mosbench/tmpfs-separate/10/log/ -name "*prog" | head -n 1)

Thats what I am getting now:
```
~/hydra/src/emulator$ ./emulator.py -i ../samples/oracle/btrfs-10.image -t btrfs -v -p $(find /tmp/mosbench/tmpfs-separate/10/log/ -name "*prog" | head -n 1)
find: ‘/tmp/mosbench/tmpfs-separate/10/log/’: No such file or directory
-bash: ./emulator.py: /usr/bin/python2: bad interpreter: No such file or directory

```

**Comment by squizz617** [comment]
Ah, seems like Ubuntu 20.04 does not ship with python 2 installed anymore.
Please install python2:
```
$ sudo apt update
$ sudo apt install python2
```
(ref: https://linuxconfig.org/install-python-2-on-ubuntu-20-04-focal-fossa-linux)

**Comment by jahidhasanlinix** [comment]
> Ah, seems like Ubuntu 20.04 does not ship with python 2 installed anymore. Please install python2:
> 
> ```
> $ sudo apt update
> $ sudo apt install python2
> ```
> 
> (ref: https://linuxconfig.org/install-python-2-on-ubuntu-20-04-focal-fossa-linux)

After installing following command of python2 I am getting this:
`~/hydra/src/emulator$ ./emulator.py -i ../samples/oracle/btrfs-10.image -t btrfs -v -p $(find /tmp/mosbench/tmpfs-separate/10/log/ -name "*prog" | head -n 1)
find: ‘/tmp/mosbench/tmpfs-separate/10/log/’: No such file or directory
usage: emulator.py [-h] -i IMG -t TYPE -p PROG [-c CRASHED] [-r] [-v] [-m]
                   [-d] [-f]
emulator.py: error: argument -p: expected one argument`

**Comment by jahidhasanlinix** [comment]
```
~/hydra/src$ ./run.py -t btrfs -c 4 -l 10 -g 1
/tmp/mosbench/tmpfs-separate/10/tmp already exists
/tmp/mosbench/tmpfs-separate/10/log already exists
in-btrfs-1 already exists
out-btrfs-1 already exists
AFL_SKIP_BIN_CHECK=1 ./combined/afl-image-syscall/afl-fuzz -S fuzzer_btrfs-cpu4log10grp1 -b shm_btrfs-4 -s fs/btrfs/btrfs_wrapper.so -e samples/oracle/btrfs-10.image -y seed -i in-btrfs-1 -o out-btrfs-1 -u 4 -- lkl/tools/lkl/btrfs-combined-consistency -t btrfs -i samples/oracle/btrfs-10.image -e emulator/emulator.py -l /tmp/mosbench/tmpfs-separate/10/log -d "/tmp/mosbench/tmpfs-separate/10/" -r -p @@
afl-fuzz 2.52b by <lcamtuf@google.com>
[+] [fs-fuzz] shm name to store image buffer: shm_btrfs-4
[+] [fs-fuzz] target wrapper (.so) path: fs/btrfs/btrfs_wrapper.so
[+] [fs-fuzz] seed image path: samples/oracle/btrfs-10.image
[+] [fs-fuzz] syscall input directory: seed
[+] You have 64 CPU cores and 1 runnable tasks (utilization: 2%).
[+] Try parallel jobs - see docs/parallel_fuzzing.txt.
[+] Found a free CPU core, binding to #4.
[*] Checking core_pattern...

[-] Hmm, your system is configured to send core dump notifications to an
    external utility. This will cause issues: there will be an extended delay
    between stumbling upon a crash and having this information relayed to the
    fuzzer via the standard waitpid() API.

    To avoid having crashes misinterpreted as timeouts, please log in as root
    and temporarily modify /proc/sys/kernel/core_pattern, like so:

    echo core >/proc/sys/kernel/core_pattern

[-] PROGRAM ABORT : Pipe at the beginning of 'core_pattern'
         Location : check_crash_handling(), afl-fuzz.c:7540

Fuzzer stopped. You can find buggy test cases in /tmp/mosbench/tmpfs-separate/10/log
```

**Comment by squizz617** [comment]
Have you re-booted after you opened the issue? If so, please run `sudo ./prepare_fuzzing` (step 4) again.

**Comment by jahidhasanlinix** [comment]
> Have you re-booted after you opened the issue? If so, please run `sudo ./prepare_fuzzing` (step 4) again.

I just followed the step 4, and now I can see the fuzzer but, one question, it stopped within few seconds when I tried with `./run.py -t btrfs -c 4 -l 10 -g 1` this

**Comment by squizz617** [comment]
>  it stopped within few seconds

Hydra was originally implemented for Ubuntu 18.04, and it seems that there is a compatibility issue on Ubuntu 20.04. Someone recently reported the issue, and we're working on a fix. I will let you know as soon as this is resolved.

**Comment by jahidhasanlinix** [comment]
Based on line#72 `fs/{2}/{2}_wrapper.so -e samples/oracle/{2}-.image -y seed -i {3} -o {4} -u {5} -- lkl/tools/lkl/{2}-combined-consistency -t {2} -i samples/oracle/{2}-.image`
- Whats that {2} refering here and wrapper.so file
- seed -i {3} -o {4} -u {5}: this instruction for what reason
- `samples/oracle/{2}-.image`- if I wanna use some different .image file here, If I wanna use other .image file does this syntax is the correct format or I need to change {2} into btrfs or ext4-`samples/oracle/{2}-'+str(i)+'.image`

**Comment by jahidhasanlinix** [comment]
> > it stopped within few seconds
> 
> Hydra was originally implemented for Ubuntu 18.04, and it seems that there is a compatibility issue on Ubuntu 20.04. Someone recently reported the issue, and we've been working on a fix. I will let you know as soon as this is resolved.

Got it, that really helpful. I appreaciate your help very much:)

**Comment by squizz617** [comment]
> Based on line#72 `fs/{2}/{2}_wrapper.so -e samples/oracle/{2}-.image -y seed -i {3} -o {4} -u {5} -- lkl/tools/lkl/{2}-combined-consistency -t {2} -i samples/oracle/{2}-.image`
> 
> * Whats that {2} refering here and wrapper.so file
> * seed -i {3} -o {4} -u {5}: this instruction for what reason
> * `samples/oracle/{2}-.image`- if I wanna use some different .image file here, If I wanna use other .image file does this syntax is the correct format or I need to change {2} into btrfs or ext4- eg:`samples/oracle/{2}-'+str(i)+'.image`

`{i}` are replaced by the i-th argument of `format()` following the string.
Please refer to python2's format string documentation (https://docs.python.org/2/library/string.html#format-examples) for further information.

**Comment by jahidhasanlinix** [comment]
> > Based on line#72 `fs/{2}/{2}_wrapper.so -e samples/oracle/{2}-.image -y seed -i {3} -o {4} -u {5} -- lkl/tools/lkl/{2}-combined-consistency -t {2} -i samples/oracle/{2}-.image`
> > 
> > * Whats that {2} refering here and wrapper.so file
> > * seed -i {3} -o {4} -u {5}: this instruction for what reason
> > * `samples/oracle/{2}-.image`- if I wanna use some different .image file here, If I wanna use other .image file does this syntax is the correct format or I need to change {2} into btrfs or ext4- eg:`samples/oracle/{2}-'+str(i)+'.image`
> 
> `{i}` is replaced with the i-th argument of `format()` following the string. Please refer to python2's format string documentation (https://docs.python.org/2/library/string.html#format-examples) for further information.

I see that helpful. I will check it, Btw I sent you an email yesterday, please kindly on your free time you can answer those question, some basic information thus did not create any issue here. And you can close this issue now as its resolved except the compatibility issue with Ubuntu 20. Thanks again for your help.

**Comment by jahidhasanlinix** [comment]
I guess I got another question before you close it, based on line #72, what would {0}, {1}, {2}, {3}, {4}, {5} and {6} be in that line? just make myself little clear about those argument.

**Comment by squizz617** [comment]
As I mentioned above, `{i}` is replaced with the i-th argument of `format()` following the string. So, 0: instance_name, 1: shm_name, 2: args.fstype, and so on.

Closing!
