### ISSUE TITLE
How to debug hangs?

### ISSUE THREAD

**Issue by ltx2018** [sslab-gatech/hydra#2]
while fuzzing ext4 i get  this:
![image](https://user-images.githubusercontent.com/50396812/72156472-96006f80-33f0-11ea-9e57-dd6eeeb1676f.png)
and i found some file in src/out-ext4-*/fuzzer_ext4-*/hangs, but no logs  in mosbench/tmpfs-separate/, then how can i debug these hangs?

**Comment by jahidhasanlinix** [comment]
@squizz617 Can you please suggest how can I debug hangs (eg: `id:000000,src:000247,op:fs-havoc-generate,rep:4`)? What process to follow for finding the root cause of a hangs? Thank you. @ltx2018  @tsgates
