### ISSUE TITLE
Question about new image 

### ISSUE THREAD

**Issue by fanjiaxin23** [sslab-gatech/hydra#20]
@squizz617  I have few specific question to ask, 
1. does hydra able to run external image filesys or its not feasible for that?
2. What are the parameters or code need to modify to run on hydra-fuzzer?

**Comment by squizz617** [comment]
Hi. With a few modifications, you can use your own file system image with Hydra.

1. The system call emulator of SymC3 initializes the initial image state [here](https://github.com/sslab-gatech/hydra/blob/master/src/emulator/utils.py#L9-L148). You have to modify `init_img` to emulate the structure of your own image, i.e., inodes and their inode numbers, hard and soft links, attributes including mode, size, directory entry, and so on. You can refer to how the structure of the existing sample images are translated in the code.
2. Modify the runner script (`run.py`) to point to your image. Specifically, change all occurrences of `samples/oracle/{2}-10.image` to the path to your image [here](https://github.com/sslab-gatech/hydra/blob/master/src/run.py#L72).

**Comment by squizz617** [comment]
You can mount the image to check the directory structure and run `stat` on the directory and files to retrieve the attributes associated with each inode.

For example, if you want to get the information of the `btrfs-10.image`:
```sh
$ pwd
/path_to_hydra/src/samples/oracle
$ mkdir /tmp/mount
$ sudo mount -t btrfs btrfs-10.image /tmp/mount
$ tree /tmp/mount
/tmp/mount
└── foo
    └── bar
        ├── acl
        ├── æøå
        ├── baz
        ├── fifo
        ├── hln
        ├── sln -> mnt/foo/bar/baz
        └── xattr

2 directories, 7 files

$ stat /tmp/mount/foo
  File: /tmp/mount/foo
  Size: 6         	Blocks: 0          IO Block: 4096   directory
Device: 3bh/59d	Inode: 257         Links: 1
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-06-07 14:45:06.529131500 -0400
Modify: 2018-06-30 22:51:07.621005310 -0400
Change: 2018-06-30 22:51:07.621005310 -0400
 Birth: -

$ stat /tmp/mount/foo/bar/hln
  File: /tmp/mount/foo/bar/hln
  Size: 12        	Blocks: 8          IO Block: 4096   regular file
Device: 3bh/59d	Inode: 259         Links: 2
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-06-30 22:51:07.625005355 -0400
Modify: 2018-06-30 22:51:07.625005355 -0400
Change: 2018-06-30 22:51:07.629005399 -0400
 Birth: -
```
As shown above, `stat` reveals all the required information including the inode id, path and filename, type, mode, size, and the number of links.

**Comment by squizz617** [comment]
Please feel free to reopen this for any follow-up questions!

**Comment by squizz617** [comment]
> after I mount the image file it shows below thing, literally shows nothing

What's supposed to be in the image? Could you share the image file? Normally when you mount an image, you should be able to see the contents. If nothing's showing up, the image really contains nothing, or is corrupted.

>  if i would like to create something similar to hydra image file for say ext4, what are the steps I should follow

You can follow the steps described [here](https://thiscouldbebetter.wordpress.com/2021/10/23/creating-an-ext4-filesystem-image-file/) to create an empty image file (ext4 in this case), mount it, create directories and files as you wish, and then umount to keep the changes.

**Comment by bvhoang91** [comment]
Hi,
I created new image by following commands (empty image, I did not mount it):
- dd if=/dev/zero of=ext4.img bs=4k count=2048
- mkfs.ext4 ext4.img
update the image path in run.py, but got an error:
![image](https://user-images.githubusercontent.com/10704702/173095208-7f1eea06-867c-47d2-9203-d344daec769c.png)
the value of pos is 16438, the  value of len is181736
Do you know how to fix this issue?

Other issue is seems that emulator/emulator.py (this script will call untils.py) is not preformed when I run run.py, I modified emulator.py to make it failed but run.py still work with image in samples/oracle

Br/Hoang
