### ISSUE TITLE
How to apply it to the mainline version, and what exactly needs to be adapted?

### ISSUE THREAD

**Issue by uestcmahone** [sslab-gatech/hydra#3]
Is it necessary to adapt lkl to the mainline version, and what changes do I need to make at the same time?

**Comment by squizz617** [comment]
The build script clones our custom lkl from `https://github.com/sslab-gatech/lkl`. For the time being, if you need the mainline version of lkl, you need to merge the mainline branch into the custom lkl repository yourself.
