### ISSUE TITLE
Tested ext4 36h+ and reported 398 uniq crashes?

### ISSUE THREAD

**Issue by uestcmahone** [sslab-gatech/hydra#5]
Tested ext4 36h+ and reported 398 uniq crashes. I doubt this. Is there anything wrong?
```
 american fuzzy lop 2.52b (fuzzer_ext4-cpu4log4grp4)

┌─ process timing ─────────────────────────────────────┬─ overall results ─────┐
│        run time : 1 days, 12 hrs, 40 min, 3 sec      │  cycles done : 97     │
│   last new path : 0 days, 0 hrs, 24 min, 6 sec       │  total paths : 3658   │
│ last uniq crash : 0 days, 22 hrs, 12 min, 26 sec     │ uniq crashes : 398    │
│  last uniq hang : 1 days, 12 hrs, 10 min, 13 sec     │   uniq hangs : 5      │
```

**Comment by squizz617** [comment]
The "unique crashes" follows the notion of AFL, based on the edge coverage. Thus, the found cases require further triage, i.e., checking the log for root cause, to determine the uniqueness.

**Comment by uestcmahone** [comment]
Thank you for comment, Dr. Kim！

**Comment by jahidhasanlinix** [comment]
@uestcmahone @squizz617  how can I debug or find the root cause of hangs that it generated? Any suggestions, Thank you.
