### ISSUE TITLE
Expand to other filesystems?

### ISSUE THREAD

**Issue by uestcmahone** [sslab-gatech/hydra#7]
4.	Hydra has supported ext4,btrfs,f2fs and xfs, can it be extended to other filesystems, such as ubifs, nfs, cifs, etc?

**Comment by squizz617** [comment]
Hydra currently is best suited for fuzzing local (i.e., single-node) file systems, and extending it to support network file systems should be possible but may require some extra work.

**Comment by uestcmahone** [comment]
OK, I got it, and I will have a try, Thanks!
