### ISSUE TITLE
How do the raw images generate?

### ISSUE THREAD

**Issue by uestcmahone** [sslab-gatech/hydra#8]
5.	How are hydra/src/samples/oracle/*. image generated, what are the difference between * -00.image and * -10.image, can images of other filesystems be made in the same way?

**Comment by squizz617** [comment]
To create those base images, we utilized a simple script which does
- dd new_disk
- mkfs new_disk
- mount new_disk
- cd mount_point
- mkdir foo
- mkdir foo/bar
- touch foo/bar/baz
...
There's no restriction regarding the base image, and the only difference between -00.image and -10.image is the existence of a FIFO file.

**Comment by uestcmahone** [comment]
Thank you very much for your answers! Dr. Kim.

**Comment by DerZc** [comment]
Hi @squizz617, could you please tell me where can I found this script to create a new image? Thank you very much!
